language: go

go:
  - 1.8

sudo: false

dist: trusty

install:
  - go get golang.org/x/tools/cmd/cover
  - make lint-deps

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: ci
      script: make ci
cache:
  directories:
  - .ethereumtest
